name: Security Audit & License Compatibility

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run cargo-deny
      uses: EmbarkStudios/cargo-deny-action@v1