name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Run cargo-deny
      uses: actions-rs/deny-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
